kubernetes_conf:
  - {path: '/etc/kubernetes/config', regexp: '^KUBE_LOGTOSTDERR=', line: 'KUBE_LOGTOSTDERR="--logtostderr=true"'}
  - {path: '/etc/kubernetes/config', regexp: '^KUBE_LOG_LEVEL=', line: 'KUBE_LOG_LEVEL="--v=0"'}
  - {path: '/etc/kubernetes/config', regexp: '^KUBE_ALLOW_PRIV=', line: 'KUBE_ALLOW_PRIV="--allow-privileged=false"'}
  - {path: '/etc/kubernetes/config', regexp: '^KUBE_MASTER=', line: 'KUBE_MASTER="--master=http://centos7-kube01-master:8080"'}

etcd_confg:
  - {path: '/etc/etcd/etcd.conf', regexp: '^ETCD_NAME=', line: 'ETCD_NAME=default'}
  - {path: '/etc/etcd/etcd.conf', regexp: '^ETCD_DATA_DIR=', line: 'ETCD_DATA_DIR="/var/lib/etcd/default.etcd"'}
  - {path: '/etc/etcd/etcd.conf', regexp: '^ETCD_LISTEN_CLIENT_URLS=', line: 'ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379"'}
  - {path: '/etc/etcd/etcd.conf', regexp: '^ETCD_ADVERTISE_CLIENT_URLS=', line: 'ETCD_ADVERTISE_CLIENT_URLS="http://0.0.0.0:2379"'}

apiserv_conf:
  - {path: '/etc/kubernetes/apiserver', regexp: '', line: ''}
  - {path: '/etc/kubernetes/apiserver', regexp: '', line: ''}
  - {path: '/etc/kubernetes/apiserver', regexp: '', line: ''}
  - {path: '/etc/kubernetes/apiserver', regexp: '', line: ''}
  - {path: '/etc/kubernetes/apiserver', regexp: '', line: ''}
  - {path: '/etc/kubernetes/apiserver', regexp: '', line: ''}