kubernetes_conf:
  - {path: '/etc/kubernetes/config', regexp: '^KUBE_LOGTOSTDERR=', line: 'KUBE_LOGTOSTDERR="--logtostderr=true"'}
  - {path: '/etc/kubernetes/config', regexp: '^KUBE_LOG_LEVEL=', line: 'KUBE_LOG_LEVEL="--v=0"'}
  - {path: '/etc/kubernetes/config', regexp: '^KUBE_ALLOW_PRIV=', line: 'KUBE_ALLOW_PRIV="--allow-privileged=false"'}
  - {path: '/etc/kubernetes/config', regexp: '^KUBE_MASTER=', line: 'KUBE_MASTER="--master=http://centos7-kube01-master:8080"'}