kubernetes_conf:
  - {path: '/etc/kubernetes/config', regexp: '^KUBE_LOGTOSTDERR=', line: 'KUBE_LOGTOSTDERR="--logtostderr=true"'}
  - {path: '/etc/kubernetes/config', regexp: '^KUBE_LOG_LEVEL=', line: 'KUBE_LOG_LEVEL="--v=0"'}
  - {path: '/etc/kubernetes/config', regexp: '^KUBE_ALLOW_PRIV=', line: 'KUBE_ALLOW_PRIV="--allow-privileged=false"'}
  - {path: '/etc/kubernetes/config', regexp: '^KUBE_MASTER=', line: 'KUBE_MASTER="--master=http://centos7-kube01-master:8080"'}

kubelet_conf:
  - {path: '/etc/kubernetes/kubelet', regexp: '^KUBELET_ADDRESS=', line: 'KUBELET_ADDRESS="--address=0.0.0.0"'}
  - {path: '/etc/kubernetes/kubelet', regexp: '^KUBELET_PORT=', line: 'KUBELET_PORT="--port=10250"'}
  - {path: '/etc/kubernetes/kubelet', regexp: '^KUBELET_HOSTNAME=', line: 'KUBELET_PORT="--hostname-override={{ ansible_hostname }}:8080"'}
  - {path: '/etc/kubernetes/kubelet', regexp: '^KUBELET_API_SERVER=', line: 'KUBELET_ARGS=""'}
  - {path: '/etc/kubernetes/kubelet', regexp: '^KUBELET_ARGS=', line: ''}

flanneld_conf:
  - {path: '/etc/sysconfig/flanneld', regexp: '^FLANNEL_ETCD_ENDPOINTS=', line: 'FLANNEL_ETCD_ENDPOINTS="http://centos7-kube01-master:2379"'}
  - {path: '/etc/sysconfig/flanneld', regexp: '^FLANNEL_ETCD_PREFIX=', line: 'FLANNEL_ETCD_PREFIX="/kube-centos/network"'}
  - {path: '/etc/sysconfig/flanneld', regexp: '^FLANNEL_OPTIONS=', line: '#FLANNEL_OPTIONS=""'}

services_on_minions:
  - {name: 'kube-proxy', state: 'restarted'}
  - {name: 'kubelet', state: 'restarted'}
  - {name: 'docker', state: 'restarted'}
  - {name: 'flanneld', state: 'restarted'}