---

- name: setup roles
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
    state: present
    enabled: yes
  with_items:
    - {{ kube_repository }}
  register: yum_kube_repo

- name: install packages
  when: yum_kube_repo is defined
  yum:
    name:
    state:
  register: yum_package_install
  with_items:
    - kube_packages

- name: hosts file template
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: resolv.conf file template
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

- name:
  systemd:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    enabled: "{{ item.enabled }}"
  with_items:
    - turn_off_services