---

- name: setup kubernetes_config
  lineinfile:
    path: '{{ item.path }}'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - "{{ kubernetes_conf }}"

- name: setup etcd
  lineinfile:
    path: '{{ item.path }}'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - "{{ etcd_conf }}"
    
- name: setup kubernetes_apiserver
  lineinfile:
    path: '{{ item.path }}'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - "{{ apiserv_conf }}"

- name: etcd start
  systemd:
    name: etcd
    state: started
    enabled: yes

- name: etcdctl mkdir
  command: 'etcdctl mkdir /kube-centos/network'

- name: etcd mk
  command: 'etcdctl mk /kube-centos/network/config "{ \"Network\": \"172.30.0.0/16\", \"SubnetLen\": 24, \"Backend\": { \"Type\": \"vxlan\" } }"'

- name: setup flanneld
  lineinfile:
    path: '{{ item.path }}'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - "{{ flanneld_conf }}"

- name: start services
  systemd:
    name: '{{ item.name }}'
    state: '{{ item.state }}'
    enabled: yes
  with_items:
    - "{{ services_on_master }}"